# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    desc "Import Certificates and Provisioning Profile"
    private_lane :import_certificates_and_provisioning_profile do
        create_keychain(
            name: "iPhone Distribution: bravesoft inc.",
            password: ENV["KEYCHAIN_PASSWORD"],
            timeout: 1800
        )
        import_certificate(
            certificate_path: "ios_distribution.p12",
            certificate_password: ENV["CERT_PASSWORD"],
            keychain_name: "iPhone Distribution: bravesoft inc.",
            keychain_password: ENV["KEYCHAIN_PASSWORD"]
        )

        install_provisioning_profile(path: "adhoc.mobileprovision")
    end

    desc "Archive AdHoc and send to Firebase"
    lane :adhoc do
        import_certificates_and_provisioning_profile
        build_app(workspace: "SampleGitHubActions.xcworkspace",
            scheme: "SampleGitHubActions",
            configuration: "Release",
            clean: true,
            export_options: {
            method: "ad-hoc"
        })

        firebase_app_distribution(
            app: "1:844965005712:ios:271f317188e248b3078b15",
            groups: "testgroup",
            release_notes: "ベータ版配信",
            firebase_cli_path: `which firebase`.strip()
        )
    end

end