# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :register_certificates_and_profiles do
    import_certificate(
      certificate_path: "\Users\nagairyo\Desktop\certificate.p12",
      certificate_password: "37naga04",
      keychain_name: "login"
    )
  
    import_provisioning_profile(
      profile_path: "\Users\nagairyo\Desktop\SampleGitHubActions_AdHoc_Profile.mobileprovision",
      profile_name: "SampleGitHubActions AdHoc Profile"
    )
  
    match(type: "adhoc")

    gym(
      configuration: "Release",
      workspace: "SampleGitHubActions.xcworkspace",
      scheme: "SampleGitHubActions",
      export_method: "ad-hoc"
    )
  end

  lane :distribute_to_firebase do
    firebase_app_distribution(
      app: "1:844965005712:ios:271f317188e248b3078b15",
      firebase_cli_token: "1//0eLL1G4m2bQDwCgYIARAAGA4SNwF-L9IrpVy5lvNjPC4gSDhfeN-yNXbN-7S9QKK4FqXbSQOgG9xiNlRMClZdMwj9WbwcCJn4zlI",
      groups: ["testgroup"],
      testers: "r.nagai@bravesoft.co.jp",
      release_notes: "your_release_notes"
    )
  end

end