# This is a basic workflow to help you get started with Actions

name: Xcode Build and Firebase App distribution

# Controls when the workflow will run
on:
  push:
    tags:
       - 'v*'
  
jobs:
  build_and_distribute:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Fastlane
        run: |
          gem install bundler
          bundle install

      - name: Register Certificates and Profiles
        run: bundle exec fastlane register_certificates_and_profiles

      - name: Build and Archive
        run: bundle exec fastlane build_and_archive

      - name: Distribute to Firebase
        run: bundle exec fastlane distribute_to_firebase
           
