# This is a basic workflow to help you get started with Actions

name: AdHoc Distribution

on:
  push:
    tags:
       - 'v*'


jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    # Firebaseのため
    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'
      
    - name: Bundle Install
      run: bundle install
      
    - name: CocoaPods
      run: bundle exec pod install

    - name: Keychain.p12
      run: |
        echo "${{ secrets.P12_BASE64 }}" > ios_distribution.p12.txt
        base64 --decode ios_distribution.p12.txt > ios_distribution.p12

    - name: ProvisioningProfile
      run: |
        echo "${{ secrets.PROVISIONING_BASE64 }}" > adhoc.mobileprovision.txt
        base64 --decode adhoc.mobileprovision.txt > adhoc.mobileprovision

    - name: list files
      run: ls -l


    - name: Adhoc
      env:
        PROVISIONING_BASE64: ${{ secrets.PROVISIONING_BASE64 }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        npm install -g firebase-tools
        bundle exec fastlane adhoc
