# This is a basic workflow to help you get started with Actions

name: Xcode Build and Firebase App distribution

# Controls when the workflow will run
on:
  push:
    tags:
       - 'v*'
  
jobs:
  build:
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # リポジトリにチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Xcode Sign In
        uses: apple-actions/xcode@v3
        with:
          args: 'signin'
        
      # macOSランナーにApple証明書をインストール       
      - name: Install Apple Certificate
        run: |
          echo "${{ secrets.CERTIFICATE_P12_BASE64 }}" | base64 --decode > certificate.p12
          security create-keychain -p actions actions.keychain
          security import certificate.p12 -k actions.keychain -P ${{ secrets.CERTIFICATE_PASSWORD }} -T /usr/bin/codesign
          security list-keychains -s actions.keychain
          security set-keychain-settings -t 3600 -l actions.keychain
          security unlock-keychain -p actions actions.keychain 

      # CocoaPodsインストール
      - name: Install CocoaPods
        run: |
             gem install cocoapods
             pod install
             
             
      - name: Xcode Select
        run: sudo xcode-select --switch /Applications/Xcode.app
             
                    
      # ビルド&アーカイブ
      - name: Build and Archive
        run: |
             xcodebuild -workspace YourProject.xcworkspace -scheme YourScheme -destination generic/platform=iOS archive
     # xcodebuild archive -workspace SampleGitHubActions.xcworkspace -scheme SampleGitHubActions -archivePath SampleGitHubActions.xcarchive -allowProvisioningUpdates
     # xcodebuild -workspace SampleGitHubActions.xcworkspace -scheme SampleGitHubActions archive -archivePath SampleGitHubActions.xcarchive -sdk iphoneos -configuration Release PROVISIONING_PROFILE="LRJJ99G592" CODE_SIGN_IDENTITY="iPhone Distribution: bravesoft inc." CODE_SIGN_STYLE="Manual" OTHER_CODE_SIGN_FLAGS="--keychain=build.keychain" 
     # xcodebuild -workspace SampleGitHubActions.xcworkspace -scheme SampleGitHubActions clean archive -archivePath ./build/SampleGitHubActions.xcarchive

          
      # エクスポートアーカイブ
      - name: Export Archive ipa
        run: |
          xcodebuild -exportArchive -archivePath SampleGitHubActions.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ./build
          
      # Firebase App Distributionにアップ 
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: 'testgroup'

      # アップ完了時に削除
      - name: Clean up
        run: |
           rm -rf ./build
           rm -rf YourProject.xcarchive
           
