# This is a basic workflow to help you get started with Actions

name: Xcode Build and Firebase App distribution

# Controls when the workflow will run
on:
  push:
    tags:
       - 'v*'
  
jobs:
  build:
    runs-on: macos-latest
    env:
      P12_CERTIFICATE: ${{ secrets.P12_CERTIFICATE }}
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # リポジトリにチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3
        

      # CocoaPodsインストール
      - name: Install CocoaPods
        run: |
             gem install cocoapods
             pod install
             
      # ビルド&アーカイブ
      - name: Build and Archive
        run: |
             xcodebuild -workspace SampleGitHubActions.xcworkspace -scheme SampleGitHubActions clean archive -archivePath ./build/SampleGitHubActions.xcarchive
     #xcodebuild -workspace YourProject.xcworkspace -scheme YourScheme archive -archivePath YourApp.xcarchive -sdk iphoneos -configuration Release PROVISIONING_PROFILE="UUID_OF_YOUR_PROVISIONING_PROFILE" CODE_SIGN_IDENTITY="iPhone Distribution: YourCompany" CODE_SIGN_STYLE="Manual" OTHER_CODE_SIGN_FLAGS="--keychain=build.keychain"
          
      # エクスポートアーカイブ
      - name: Export Archive ipa
        run: |
          xcodebuild archive -exportArchive -archivePath ./build/SampleGitHubActions.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ./build
           
     # Firebaseインストール
      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
          
     # Nodeインストール
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          
     # Firebaseログイン
      - name: Authenticate Firebase
        run: firebase login:ci --interactive

     # Firebase App Distributionにipaファイルアップロード
      - name: Distribute to Firebase App Distribution
        run: firebase appdistribution:distribute ./build/SampleGitHubActions.ipa --app 1:844965005712:ios:271f317188e248b3078b15 --groups "testgroup"
